# Generated by Django 5.1.2 on 2024-10-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesListFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(max_length=255)),
                ('choices_list_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.choiceslistfield')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.student')),
            ],
            options={
                'db_table': 'choices_list_field_response',
            },
        ),
    ]
