# Generated by Django 5.1.2 on 2024-10-30 20:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_choiceslistfieldresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceslistfield',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), default=['a'], size=None),
            preserve_default=False,
        ),
    ]
